<a href="https://colab.research.google.com/github/mariatozi/projetospessoais/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install yfinance --upgrade --no--cache-dir
import yfinance as yf
import pandas_datareader.data as web
yf.pdr_override()

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --no--cache-dir

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
!pip uninstall pyfolio

Found existing installation: pyfolio 0.9.2+75.g4b901f6
Uninstalling pyfolio-0.9.2+75.g4b901f6:
  Would remove:
    /usr/local/lib/python3.10/dist-packages/pyfolio-0.9.2+75.g4b901f6.dist-info/*
    /usr/local/lib/python3.10/dist-packages/pyfolio/*
Proceed (Y/n)? y
  Successfully uninstalled pyfolio-0.9.2+75.g4b901f6

In [35]:
!pip install git+https://github.com/quantopian/pyfolio
import pyfolio as pf
import warnings
warnings.filterwarnings('ignore')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/quantopian/pyfolio
  Cloning https://github.com/quantopian/pyfolio to /tmp/pip-req-build-srlz8wiz
  Running command git clone --filter=blob:none --quiet https://github.com/quantopian/pyfolio /tmp/pip-req-build-srlz8wiz
  Resolved https://github.com/quantopian/pyfolio to commit 4b901f6d73aa02ceb6d04b7d83502e5c6f2e81aa
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ipython>=3.2.3 in /usr/local/lib/python3.10/dist-packages (from pyfolio==0.9.2+75.g4b901f6) (7.34.0)
Requirement already satisfied: matplotlib>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from pyfolio==0.9.2+75.g4b901f6) (3.7.1)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.10/dist-packages (from pyfolio==0.9.2+75.g4b901f6) (1.22.4)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.10/dist-packages (from pyfolio==0.9.2+75.g4b901f6) (1.5.3)
Requirement already satisfied: pytz>=2014.10 in /usr/local/lib/python3.10/dist-packages (from pyfolio==0.9.2+75.g4b901f6) (2022.7.1)
Requirement already satisfied: scipy>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from pyfolio==0.9.2+75.g4b901f6) (1.10.1)
Requirement already satisfied: scikit-learn>=0.16.1 in /usr/local/lib/python3.10/dist-packages (from pyfolio==0.9.2+75.g4b901f6) (1.2.2)
Requirement already satisfied: seaborn>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from pyfolio==0.9.2+75.g4b901f6) (0.12.2)
Requirement already satisfied: empyrical>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from pyfolio==0.9.2+75.g4b901f6) (0.5.5)
Requirement already satisfied: pandas-datareader>=0.2 in /usr/local/lib/python3.10/dist-packages (from empyrical>=0.5.0->pyfolio==0.9.2+75.g4b901f6) (0.10.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (67.7.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (0.18.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (3.0.38)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (2.14.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (0.1.6)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (4.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.4.0->pyfolio==0.9.2+75.g4b901f6) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.4.0->pyfolio==0.9.2+75.g4b901f6) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.4.0->pyfolio==0.9.2+75.g4b901f6) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.4.0->pyfolio==0.9.2+75.g4b901f6) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.4.0->pyfolio==0.9.2+75.g4b901f6) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.4.0->pyfolio==0.9.2+75.g4b901f6) (8.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.4.0->pyfolio==0.9.2+75.g4b901f6) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=1.4.0->pyfolio==0.9.2+75.g4b901f6) (2.8.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.16.1->pyfolio==0.9.2+75.g4b901f6) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.16.1->pyfolio==0.9.2+75.g4b901f6) (3.1.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (0.8.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio==0.9.2+75.g4b901f6) (4.9.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio==0.9.2+75.g4b901f6) (2.27.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=3.2.3->pyfolio==0.9.2+75.g4b901f6) (0.2.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=1.4.0->pyfolio==0.9.2+75.g4b901f6) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio==0.9.2+75.g4b901f6) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio==0.9.2+75.g4b901f6) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio==0.9.2+75.g4b901f6) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader>=0.2->empyrical>=0.5.0->pyfolio==0.9.2+75.g4b901f6) (3.4)
Building wheels for collected packages: pyfolio
  Building wheel for pyfolio (setup.py) ... done
  Created wheel for pyfolio: filename=pyfolio-0.9.2+75.g4b901f6-py3-none-any.whl size=75761 sha256=209cc9a1bd8677299b7d9adbbf1605fa41107b04e86a8c460bfa4e866925d306
  Stored in directory: /tmp/pip-ephem-wheel-cache-r7mkbe90/wheels/25/2f/dd/558b6be9405213c9f6fdb1c5a062028a4da70862268f4116e6
Successfully built pyfolio
Installing collected packages: pyfolio
Successfully installed pyfolio-0.9.2+75.g4b901f6

In [5]:
tickers = ['ABEV3.SA','ITSA4.SA','WEGE3.SA','USIM5.SA','VALE3.SA','^BVSP']
dados_yahoo = web.get_data_yahoo(tickers, period='5y')['Adj Close']

[*********************100%***********************]  6 of 6 completed

In [6]:
dados_yahoo

             ABEV3.SA  ITSA4.SA  USIM5.SA   VALE3.SA   WEGE3.SA          ^BVSP
Date
2018-06-22  15.370569  5.988129  5.828786  33.117466   7.186804   70641.000000
2018-06-25  15.421350  5.961457  5.820646  32.531136   7.363681   70953.000000
2018-06-26  15.311318  6.061481  5.788083  33.345100   7.428847   71405.000000
2018-06-27  15.192822  5.881437  5.820646  33.214046   7.317134   70609.000000
2018-06-28  15.243607  6.028140  6.048587  33.848660   7.498666   71767.000000
...               ...       ...       ...        ...        ...            ...
2023-06-16  15.070000  9.650000  7.390000  69.669998  37.849998  118758.000000
2023-06-19  15.110000  9.770000  7.500000  69.400002  37.669998  119858.000000
2023-06-20  15.140000  9.810000  7.390000  67.610001  36.950001  119622.000000
2023-06-21  15.280000  9.890000  7.300000  66.930000  36.450001  120420.000000
2023-06-22  15.550000  9.770000  7.220000  66.570000  36.400002  118934.203125

[1239 rows x 6 columns]

In [23]:
retorno = dados_yahoo.pct_change()
retorno

            ABEV3.SA  ITSA4.SA  USIM5.SA  VALE3.SA  WEGE3.SA     ^BVSP
Date
2018-06-22       NaN       NaN       NaN       NaN       NaN       NaN
2018-06-25  0.003304 -0.004454 -0.001397 -0.017705  0.024611  0.004417
2018-06-26 -0.007135  0.016778 -0.005595  0.025021  0.008850  0.006370
2018-06-27 -0.007739 -0.029703  0.005626 -0.003930 -0.015038 -0.011148
2018-06-28  0.003343  0.024943  0.039161  0.019107  0.024809  0.016400
...              ...       ...       ...       ...       ...       ...
2023-06-16 -0.007900  0.002077 -0.001351  0.001581  0.000264 -0.003884
2023-06-19  0.002654  0.012435  0.014885 -0.003875 -0.004756  0.009263
2023-06-20  0.001985  0.004094 -0.014667 -0.025793 -0.019113 -0.001969
2023-06-21  0.009247  0.008155 -0.012179 -0.010058 -0.013532  0.006671
2023-06-22  0.017670 -0.012133 -0.010959 -0.005379 -0.001372 -0.012338

[1239 rows x 6 columns]

In [24]:
retorno_acumulado = (1 + retorno).cumprod()
retorno_acumulado.iloc[0] = 1
retorno_acumulado

            ABEV3.SA  ITSA4.SA  USIM5.SA  VALE3.SA  WEGE3.SA     ^BVSP
Date
2018-06-22  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
2018-06-25  1.003304  0.995546  0.998603  0.982295  1.024611  1.004417
2018-06-26  0.996145  1.012249  0.993017  1.006874  1.033679  1.010815
2018-06-27  0.988436  0.982183  0.998603  1.002916  1.018135  0.999547
2018-06-28  0.991740  1.006682  1.037709  1.022079  1.043394  1.015940
...              ...       ...       ...       ...       ...       ...
2023-06-16  0.980445  1.611522  1.267845  2.103724  5.266597  1.681148
2023-06-19  0.983048  1.631561  1.286717  2.095571  5.241551  1.696720
2023-06-20  0.984999  1.638241  1.267845  2.041521  5.141367  1.693379
2023-06-21  0.994108  1.651601  1.252405  2.020988  5.071795  1.704676
2023-06-22  1.011674  1.631561  1.238680  2.010118  5.064838  1.683643

[1239 rows x 6 columns]

In [25]:
carteira = 10000 * retorno_acumulado.iloc[:, :5]
carteira["saldo"] = carteira.sum(axis=1)
carteira["retorno"] = carteira["saldo"].pct_change()
carteira

,ABEV3.SA,ITSA4.SA,USIM5.SA,VALE3.SA,WEGE3.SA,saldo,retorno
Date,,,,,,,
2018-06-22,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,50000.000000,NaN
2018-06-25,10033.037976,9955.457936,9986.034679,9822.954324,10246.113592,50043.598507,0.000872
2018-06-26,9961.451765,10122.494658,9930.167670,10068.735461,10336.788103,50419.637657,0.007514
2018-06-27,9884.359017,9821.827762,9986.034679,10029.163012,10181.346368,49902.730838,-0.010252
2018-06-28,9917.398855,10066.817078,10377.094747,10220.787890,10433.936948,51016.035517,0.022309
...,...,...,...,...,...,...,...
2023-06-16,9804.451267,16115.216280,12678.453787,21037.237036,52665.965181,112301.323550,-0.000131
2023-06-19,9830.475002,16315.614161,12867.172547,20955.710072,52415.505731,112384.477512,0.000740
2023-06-20,9849.993268,16382.412924,12678.453787,20415.209505,51413.673238,110739.742722,-0.014635
2023-06-21,9941.076030,16516.010450,12524.048273,20209.879693,50717.953723,109908.968168,-0.007502
2023-06-22,10116.736706,16315.614161,12386.797745,20101.175540,50648.382833,109568.706984,-0.003096

In [36]:
pf.create_full_tear_sheet(carteira["retorno"], benchmark_rets=retorno["^BVSP"])

AttributeError: ignored

In [37]:
pf.create_full_tear_sheet(carteira["retorno"], benchmark_rets=retorno["^BVSP"])

AttributeError: ignored